//
//  Comments.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSDynamoDB

class Comments: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _postId: String?
    var _postDateGMT: NSNumber?
    var _commentBody: String?
    var _userId: String?
    var _photoURL: String?
    
    class func dynamoDBTableName() -> String {

        return "pod-mobilehub-1901037061-Comments"
    }
    
    class func hashKeyAttribute() -> String {

        return "_postId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_postDateGMT"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_postId" : "postId",
               "_postDateGMT" : "postDateGMT",
               "_commentBody" : "commentBody",
               "_userId" : "userId",
               "_photoURL" : "photoURL",
        ]
    }
}
