//
//  PodList.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSDynamoDB

class PodList: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _geoHashCode: String?
    var _podId: NSNumber?
    var _createdByUserId: String?
    var _isPrivate: NSNumber?
    var _latitude: NSNumber?
    var _longitude: NSNumber?
    var _name: String?
    var _radius: NSNumber?
    var _userIdList: [String]?
    var _usernameList: [String]?
    
    class func dynamoDBTableName() -> String {

        return "pod-mobilehub-1901037061-PodList"
    }
    
    class func hashKeyAttribute() -> String {

        return "_geoHashCode"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_podId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_geoHashCode" : "GeoHashCode",
               "_podId" : "PodId",
               "_createdByUserId" : "CreatedByUserId",
               "_isPrivate" : "IsPrivate",
               "_latitude" : "Latitude",
               "_longitude" : "Longitude",
               "_name" : "Name",
               "_radius" : "Radius",
               "_userIdList" : "UserIdList",
               "_usernameList" : "UsernameList",
        ]
    }
}
