//
//  PodRequests.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSDynamoDB

class PodRequests: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _podId: NSNumber?
    var _podName: String?
    var _requestType: NSNumber?
    var _requesterID: String?
    var _requesterPhotoURL: String?
    var _requesterName: String?
    var _podGeoHash: String?

    
    class func dynamoDBTableName() -> String {

        return "pod-mobilehub-1901037061-PodRequests"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_podId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_podId" : "podId",
               "_requestType" : "requestType",
               "_requesterID" : "requesterID",
               "_requesterPhotoURL" : "requesterPhotoURL",
               "_podName" : "podName",
               "_requesterName" : "requesterName",
               "_podGeoHash" : "podGeoHash",
        ]
    }
}
