//
//  PodRequests.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSDynamoDB

class PodRequests: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _requestId: String?
    var _geoHashCode: String?
    var _podId: NSNumber?
    var _requestType: NSNumber?
    var _sendTime: NSNumber?
    var _senderName: String?
    var _sentBy: String?
    var _senderPhotoURL: String?
    var _podName: String?
    
    class func dynamoDBTableName() -> String {

        return "pod-mobilehub-1901037061-PodRequests"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_requestId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_requestId" : "RequestId",
               "_geoHashCode" : "GeoHashCode",
               "_podId" : "PodId",
               "_requestType" : "RequestType",
               "_sendTime" : "SendTime",
               "_senderName" : "SenderName",
               "_sentBy" : "SentBy",
               "_senderPhotoURL" : "SenderPhotoURL",
               "_podName" : "PodName",
        ]
    }
}
